### PR TITLE
Flatbox Revision 4 support

### PR DESCRIPTION
**Pull request by fluxcorenz**
Restore support for Flatbox Revision 4.

Tested on my own Flatbox Rev4 devices.

Default button mapping mimics Bentobox.

### CODE REVIEW

**Review by TheTrainGoes — COMMENTED** [review]
Is the extra set of defines needed on this?  Have you tested with just assigning the pin directly?

**Comment by fluxcorenz** [comment]
Absolutely it will work without. It's just much easier to determine which button connects to which pin (and how it's mapped to the GP2040 functions) with the extra set. If define space is lacking (?) it could be converted to a set of comments describing the flatbox SW number to pin number, just means that a person manually fiddling with the gp2040 button mapping in code would have to do an extra set of manual lookups via the comments.

**Comment by TheTrainGoes** [comment]
No space issues that I am aware of that you would not have run into while testing so you should have a good runway there.  

I will PM you with a few additional concerns on Discord.

**Comment by TheTrainGoes** [comment]
Hey @hurik ,

The additional concerns were more about legacy support and ensuring we had done a good sample of tests before releasing it.  

As we are seeing with the CC2.0 there are different versions and parts used on some of them which have lead to some compatibility issues.

I would like to ensure what we release has been tested as much as possible as not to leave people with a soft-bricked unit that might not know how to recover on their own.

**Pull request merged**
