### PR TITLE
Fix button layout options in docs

### PR DESCRIPTION
**Pull request by henrebotha**

### CODE REVIEW

**Comment by TheTrainGoes** [comment]
Hey @henrebotha ,

Once we push 0.4.4 we will look into some of these cleanup options.  There was some work done by someone on the main GP2040 to bring new layouts to the screen.  I am going to have them make a PR request here with those changes against 0.4.4 and we will look at merging it.

**Comment by TheTrainGoes** [comment]
Hey @henrebotha ,

Much of this will be addressed in an upcoming update to the display options overall.  I will check in again on this once those changes are in place.

**Comment by henrebotha** [comment]
@TheTrainGoes cool, feel free to close this if it's not going to be merged as is. We can always reopen it later.

**Comment by TheTrainGoes** [comment]
@henrebotha until we get the web-config updated I have done a massive overhaul of the config file.

**Pull request closed without merging**
